apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-management-service
      aadpodidbinding: $DOC_MI_NAME
  template:
    metadata:
      labels:
        app: document-management-service
        aadpodidbinding: $DOC_MI_NAME
    spec:
      hostAliases:
      - ip: "10.13.3.60"
        hostnames:
          - "rer-core-services"
      - ip: "10.13.3.30"
        hostnames:
          - "companies-house-service"
      - ip: "10.13.3.20"
        hostnames:
          - "address-lookup-service"
      - ip: "10.13.3.10"
        hostnames: 
          - "adb2c-user-service"
      - ip: "10.13.3.50"
        hostnames:
          - "internal-web-app"
      containers:
      - name: document-management-service
        image: $ACR.azurecr.io/document-management-service:latest
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY 
            value: '$INSTRUMENTATION_KEY'
          - name: ASPNETCORE_ENVIRONMENT
            value: '$DOTNETENVIRONMENT_NAME'
      imagePullSecrets:
            - name: acr-secret