apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: address-lookup-service.ofg-dev-i-address-lookup.svc.cluster.local
  namespace: ofg-dev-i-address-lookup
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /Address/[^/]*
    name: GET /Address/{postcode}
    responseClasses:
    - condition:
        status:
          max: 200
          min: 200
    - condition:
        status:
          max: 404
          min: 404
