apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: ContainerResources
metadata:
  name: containerresources
spec:
  match:
    namespaces:
      - ofg-$ENV-$FACING-address-lookup
      - ofg-$ENV-$FACING-companies-house
      - ofg-$ENV-$FACING-document-management
      - ofg-$ENV-$FACING-notification
      - ofg-$ENV-$FACING-rer-core
      - ofg-$ENV-$FACING-web-app
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]