trigger:
  - master

stages:
  - stage: Sbx
    jobs:
      - deployment: DeploySboxCoreInternal
        displayName: deploy Sbox Core Internal
        pool:
          vmImage: "ubuntu-latest"
        environment: "sbx"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@1
                  displayName: Get service principal credentials
                  inputs:
                     azureSubscription: "Ofgem-RER-Sbox"
                     scriptLocation: inlineScript
                     addSpnToEnvironment: true
                     failOnStandardError: true
                     inlineScript: |
                       # Define environment variables
                       export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                       export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
                       export ARM_CLIENT_ID=$servicePrincipalId
                       export ARM_CLIENT_SECRET=$servicePrincipalKey

                       # Set pipeline variables for use in subsequent tasks
                       echo "##vso[task.setvariable variable=arm_subscription_id]${ARM_SUBSCRIPTION_ID}"
                       echo "##vso[task.setvariable variable=arm_tenant_id]${ARM_TENANT_ID}"
                       echo "##vso[task.setvariable variable=arm_client_id]${ARM_CLIENT_ID}"
                       echo "##vso[task.setvariable variable=arm_client_secret]${ARM_CLIENT_SECRET}"
                - task: AzureCLI@1
                  displayName: Connect to AKS Internal
                  inputs:
                    azureSubscription: "Ofgem-RER-Sbox"
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    failOnStandardError: false
                    inlineScript: |
                      az aks get-credentials \
                        --name ofg-sbx-i-aks \
                        --resource-group  ofg-sbx-i-aks-rg \
                        --admin --overwrite-existing                    
                - task: AzureCLI@1
                  displayName: Deploy RER Services
                  inputs:
                    azureSubscription: "Ofgem-RER-Sbox"
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    failOnStandardError: true
                    inlineScript: |
                      source ./environments/sbx/env-int.sh
                      source ./environments/env-all.sh
                      kubectl config use-context ofg-sbx-i-aks-admin
                      kustomize build ./services/ | envsubst |  kubectl apply -f -

      - deployment: DeploySboxCoreExternal
        displayName: deploy Sbox Core External
        pool:
          vmImage: "ubuntu-latest"
        environment: "sbx"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@1
                  displayName: Get service principal credentials
                  inputs:
                    azureSubscription: "Ofgem-RER-Sbox"
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    failOnStandardError: true
                    inlineScript: |
                      # Define environment variables
                      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                      export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
                      export ARM_CLIENT_ID=$servicePrincipalId
                      export ARM_CLIENT_SECRET=$servicePrincipalKey

                      # Set pipeline variables for use in subsequent tasks
                      echo "##vso[task.setvariable variable=arm_subscription_id]${ARM_SUBSCRIPTION_ID}"
                      echo "##vso[task.setvariable variable=arm_tenant_id]${ARM_TENANT_ID}"
                      echo "##vso[task.setvariable variable=arm_client_id]${ARM_CLIENT_ID}"
                      echo "##vso[task.setvariable variable=arm_client_secret]${ARM_CLIENT_SECRET}"
                
                - task: AzureCLI@1
                  displayName: Connect to AKS
                  inputs:
                    azureSubscription: "Ofgem-RER-Sbox"
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    failOnStandardError: false
                    inlineScript: |
                      az aks get-credentials \
                        --name ofg-sbx-e-aks \
                        --resource-group  ofg-sbx-e-aks-rg \
                        --admin --overwrite-existing
                 
                - task: AzureCLI@1
                  displayName: Deploy RER Services
                  inputs:
                    azureSubscription: "Ofgem-RER-Sbox"
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    failOnStandardError: true
                    inlineScript: |
                      source ./environments/sbx/env-ext.sh
                      source ./environments/env-all.sh
                      kubectl config use-context ofg-sbx-e-aks-admin
                      kustomize build ./services/external-web/ | envsubst |  kubectl apply -f -
