apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-cron-job
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-cron-job
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -c
            - curl http://rer-core-services/DailyTasks
          restartPolicy: OnFailure